### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sakamoto824** [PanDoreS/xiaomi-yeelight-api-tools#1]
Dear Develorper,

When I run this .py it show me  
File "yeelight.py", line 72
    bulb_2execute = args.id
                         ^
What cat I do?

Thanks,

**Comment by PanDoreS** [comment]
Hi,

It still in developpement phase, so it's really buggy right now ;)
Just come back in few weeks, it'll be surely ready.
It's inspired from : https://www.yeelight.com/en_US/developer, go check their Python script if you want :)

**Comment by sakamoto824** [comment]
Hi,
when I run this program it show me
File "yeelight.py", line 72
bulb_2execute = args.id  
What do I need to do or setting?

Notebook > Mi WiFi > Yeelight
Thank for your help :100: 

Regards,
